# Generated by Django 3.2.16 on 2024-04-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240407_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_created',
            new_name='created_at',
        ),
    ]
